### ISSUE TITLE
Trouble emmaking takehiro.o

### ISSUE THREAD

**Issue by shibby4** [akrennmair/libmp3lame-js#1]
Hi,

I was trying to build the project because it seems very interesting but I'm having problems with the emmake part. Specifically, running each .o separately I found that takehiro.o would not compile. Did you have any problems of the sort? Did you tweak your emscripten settings in any way? Any clue what might have gone wrong?

Thanks in advance.

Environment info:
OS: Ubuntu LInux 13.04 64bit desktop edition
emscripten: emcc (Emscripten GCC-like replacement) 1.3.6 (commit 17da251d334ce62d633d51f874b92e19ad9dbf45)
clang: Ubuntu clang version 3.2-1~exp9ubuntu1 (tags/RELEASE_32/final) (based on LLVM 3.2)
llvm: LLVM version 3.2 Ubuntu 3.2-2ubuntu5
nodejs: v0.6.19

I also tried with a 32bit VM of ubuntu 12.04 but had the same results.

Emscripten outputs the following:

undefined:1714
      for (var i = 1; i < typeData.fields.length; i++) {
                                  ^
TypeError: Cannot read property 'fields' of undefined
    at eval at globalEval (/opt/emscripten/src/compiler.js:105:8)
    at Array.forEach (native)
    at getGetElementPtrIndexes (eval at globalEval (/opt/emscripten/src/compiler.js:105:8))
    at finalizeLLVMFunctionCall (eval at globalEval (/opt/emscripten/src/compiler.js:105:8))
    at eval at globalEval (/opt/emscripten/src/compiler.js:105:8)
    at Object.processItem (eval at globalEval (/opt/emscripten/src/compiler.js:105:8))
    at Object.process (eval at globalEval (/opt/emscripten/src/compiler.js:105:8))
    at Object.solve (eval at globalEval (/opt/emscripten/src/compiler.js:105:8))
    at JSify (eval at globalEval (/opt/emscripten/src/compiler.js:105:8))
    at JSify (eval at globalEval (/opt/emscripten/src/compiler.js:105:8))
Traceback (most recent call last):
  File "/opt/emscripten/emscripten.py", line 753, in <module>
    _main(environ=os.environ)
  File "/opt/emscripten/emscripten.py", line 741, in _main
    temp_files.run_and_clean(lambda: main(
  File "/opt/emscripten/tools/tempfiles.py", line 38, in run_and_clean
    return func()
  File "/opt/emscripten/emscripten.py", line 749, in <lambda>
    DEBUG_CACHE=DEBUG_CACHE,
  File "/opt/emscripten/emscripten.py", line 648, in main
    jcache=jcache, temp_files=temp_files, DEBUG=DEBUG, DEBUG_CACHE=DEBUG_CACHE)
  File "/opt/emscripten/emscripten.py", line 265, in emscript
    assert len(output) == 2, 'Did not receive forwarded data in an output - process failed? We only got: ' + output[0][-3000:]
AssertionError: Did not receive forwarded data in an output - process failed? We only got: label = 17; break;
    case 17: 
      var $103=(($gi+4768)|0);
      var $104=HEAP32[(($103)>>2)];
      var $105=HEAP32[(($82)>>2)];
      var $106=(($104)|(0)) > (($105)|(0));
      if ($106) { label = 18; break; } else { label = 19; break; }
    case 18: 
      _memcpy($11, $10, 5252);
      label = 19; break;
    case 19: 
      STACKTOP = __stackBase__;
      return;
  }

}

function _count_bits($gfc, $xr, $gi, $prev_noise) {
  var label = 0;

  label = 1; 
  while(1) switch(label) {
    case 1: 
      var $1=(($gi+4780)|0);
      var $2=HEAP32[(($1)>>2)];
      var $3=((5326380+($2<<2))|0);
      var $4=HEAPF32[(($3)>>2)];
      var $5=(8206)/($4);
      var $6=(($gi+4764)|0);
      var $7=HEAPF32[(($6)>>2)];
      var $8=$7 > $5;
      if ($8) { var $_0 = 100000;label = 10; break; } else { label = 2; break; }
    case 2: 
      var $10=(($gi+2304)|0);
      _quantize_xrpow($xr, $10, $4, $gi, $prev_noise);
      var $11=(($gfc+85092)|0);
      var $12=HEAP32[(($11)>>2)];
      var $13=$12 & 2;
      var $14=(($13)|(0))==0;
      if ($14) { label = 9; break; } else { label = 3; break; }
    case 3: 
      var $16=HEAP32[(($1)>>2)];
      var $17=(($gi+4836)|0);
      var $18=HEAP32[(($17)>>2)];
      var $19=((($18)+($16))|0);
      var $20=((5326380+($19<<2))|0);
      var $21=HEAPF32[(($20)>>2)];
      var $22=$21;
      var $23=(0.634521682242439)/($22);
      var $24=$23;
      var $25=(($gi+4860)|0);
      var $26=HEAP32[(($25)>>2)];
      var $27=(($26)|(0)) > 0;
      if ($27) { var $j_033 = 0;var $sfb_034 = 0;label = 4; break; } else { label = 9; break; }
    case 4: 
      var $sfb_034;
      var $j_033;
      var $28=(($gi+4872+($sfb_034<<2))|0);
      var $29=HEAP32[(($28)>>2)];
      var $30=(($gfc+84932+($sfb_034<<2))|0);
      var $31=HEAP32[(($30)>>2)];
      var $32=(($31)|(0))!=0;
      var $33=((($29)+($j_033))|0);
      var $34=(($29)|(0)) > 0;
      var $or_cond=$32 & $34;
      if ($or_cond) { var $k_031 = $j_033;label = 5; break; } else { label = 8; break; }
    case 5: 
      var $k_031;
      var $35=(($xr+($k_031<<2))|0);
      var $36=HEAPF32[(($35)>>2)];
      var $37=$36 < $24;
      if ($37) { var $42 = 0;label = 7; break; } else { label = 6; break; }
    case 6: 
      var $39=(($gi+2304+($k_031<<2))|0);
      var $40=HEAP32[(($39)>>2)];
      var $42 = $40;label = 7; break;
    case 7: 
      var $42;
      var $43=(($gi+2304+($k_031<<2))|0);
      HEAP32[(($43)>>2)]=$42;
      var $44=((($k_031)+(1))|0);
      var $45=(($44)|(0)) < (($33)|(0));
      if ($45) { var $k_031 = $44;label = 5; break; } else { label = 8; break; }
    case 8: 
      var $46=((($sfb_034)+(1))|0);
      var $47=HEAP32[(($25)>>2)];
      var $48=(($46)|(0)) < (($47)|(0));
      if ($48) { var $j_033 = $33;var $sfb_034 = $46;label = 4; break; } else { label = 9; break; }
    case 9: 
      var $49=_noquant_count_bits($gfc, $gi, $prev_noise);
      var $_0 = $49;label = 10; break;
    case 10: 
      var $_0;

```
  return $_0;
```

  }

}

Traceback (most recent call last):
  File "/opt/emscripten/emcc", line 1333, in <module>
    final = shared.Building.emscripten(final, append_ext=False, extra_args=extra_args)
  File "/opt/emscripten/tools/shared.py", line 949, in emscripten
    assert os.path.exists(filename + '.o.js') and len(open(filename + '.o.js', 'r').read()) > 0, 'Emscripten failed to generate .js: ' + str(compiler_output)
AssertionError: Emscripten failed to generate .js: 
make: **\* [dist/libmp3lame.js] Error 1

**Comment by akrennmair** [comment]
emscripten has a bug in the optimization code which I reported here (including fix): https://github.com/kripken/emscripten/pull/865

The author required more input for test coverage, but due to various reasons, I'm currently simply unable to work on anything related to that. So my fix never got merged. The workaround is to disable optimization. I just did that in the Makefile and pushed the change. Please pull master to see the workaround. Building should work, then.

**Comment by shibby4** [comment]
thanks A LOT for your quick reply. Disabling the optimizations did the trick :smile: 
Let's hope the folks at emscripten find the time to merge your fix :wink:
